# Teilaufgabe a)

In [2]:
import pandas as pd

df = pd.read_csv("../data/stock_data.csv")

df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2009-12-31,137.089996,137.279999,134.520004,134.520004,134.520004,4523000
1,2010-01-04,136.250000,136.610001,133.139999,133.899994,133.899994,7599900
2,2010-01-05,133.429993,135.479996,131.809998,134.690002,134.690002,8851900
3,2010-01-06,134.600006,134.729996,131.649994,132.250000,132.250000,7178800
4,2010-01-07,132.009995,132.320007,128.800003,130.000000,130.000000,11030200

In [3]:
close = df[['Close']]
close.head()

        Close
0  134.520004
1  133.899994
2  134.690002
3  132.250000
4  130.000000

In [11]:
df_3 = pd.DataFrame()
df_3['close_t-3'] = df['Close'].shift(3)
df_3['close_t-2'] = df['Close'].shift(2)
df_3['close_t-1'] = df['Close'].shift(1)
df_3['target'] = df['Close']

df_3.head()

    close_t-3   close_t-2   close_t-1      target
0         NaN         NaN         NaN  134.520004
1         NaN         NaN  134.520004  133.899994
2         NaN  134.520004  133.899994  134.690002
3  134.520004  133.899994  134.690002  132.250000
4  133.899994  134.690002  132.250000  130.000000

In [ ]:
def create_dataset(df, window):
    data = pd.concat(
        [df['Close'].shift(i) for i in range(window, 0, -1)] + [df['Close']],
        axis=1
    )
    data.columns = [f'close_t-{i}' for i in range(window,0,-1)] + ['target']
    return data.dropna()

df_3 = create_dataset(df, 3)
df_5 = create_dataset(df, 5)
df_8 = create_dataset(df, 8)

print(df_3.shape)
print(df_5.shape)
print(df_8.shape)

(2253, 9)
(2256, 6)
(2258, 4)